name: Run tests & Lint

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev'

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run linter
        uses: giraffate/clippy-action@871cc4173f2594435c7ea6b0bce499cf6c2164a1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --all-features -- -D warnings
          reporter: github-pr-review

      - name: Run tests
        run: cargo test --all-features
